### ISSUE TITLE
Reusing workflows avoids duplication

### ISSUE THREAD

**Issue by jongwooo** [terraform-aws-modules/.github#29]
## Is your request related to a new offering from AWS?

N/A

## Is your request related to a problem? Please describe.

Each repository has five workflow codes(e.g. `lock.yml`, `pr-title.yml`, etc.). These workflows consist of the same code. If the workflow requirements change, the workflow for each repository must be changed individually. This makes maintenance difficult and can lead to human error.

## Describe the solution you'd like.

By abstracting into [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows), we can simplify redundant workflows.

### Example
<details>
<summary>Example code</summary>

**`terraform-aws-modules/.github/.github/workflow-templates/lock.yml`**:

```yaml
name: 'Lock Threads Template'

on: workflow_call

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
    # ...
```

**`terraform-aws-modules/terraform-aws-vpc/.github/workflows/lock.yml`**:

```yaml
name: 'Call Lock Threads'

on:
  schedule:
    - cron: '50 1 * * *'

jobs:
  call-lock:
    uses: terraform-aws-modules/.github/.github/workflow-templates/lock.yml
    with:
      secrets: inheirt
```
</details>

## References

- https://docs.github.com/en/actions/using-workflows/reusing-workflows
- https://github.com/actions/reusable-workflows

## Describe alternatives you've considered.

N/A

## Additional context

If there's nothing wrong with this issue, can I work on it?
